- name: Submit a simple job array to the SLURM controller node
  hosts: controller_node
  tasks:
    - name: Copy simple job script
      copy:
        src: roles/simple_job_array/files/simple.py
        dest: "{{ script_path }}"
    - name: Submit job array from command line using sbatch
      command: >
        sbatch --array={{ job_array }}
          --mem={{ memory_limit }}
          --time={{ time_limit }}
          --output={{ output_file }}
          --error={{ error_file }}
          --wrap="python {{ script_path }}"
