- name: Show jobs in the SLURM queue for a specific partition
  hosts: controller_node
  tasks:
    - name: Show SLURM queue in long format for partition
      command: >
        squeue -l -p {{ partition_name }}
